site_name: API de Series de Tiempo
site_url: http://apis.datos.gob.ar/series/
site_description: Documentación de la API de Series de Tiempo de la República Argentina
site_author: Datos Argentina
repo_url: https://github.com/datosgobar/series-tiempo-ar-api/

nav:
  - Inicio: index.md
  - Usuarios:
    - Comenzar a usar la API: quick_start.md
    - Filtrar y transformar las series: additional_parameters.md
    - Integrar la API en planillas de cálculo: spreadsheet_integration.md
    - Referencia API:
      - Datos: 'reference/api_reference.md'
      - Metadatos: 'reference/search_reference.md'
    - Referencia OpenAPI: https://datosgobar.github.io/series-tiempo-ar-api
  - Aplicaciones: applications.md
  - Desarrolladores:
    - Arquitectura: 'developers/arquitectura.md'
    - Instalación: 'developers/development.md'
    - Administración: 'developers/admin.md'

theme: readthedocs

extra_css:
  - css/extra.css
