site_name: API de Series de Tiempo
pages:
- Inicio: index.md
- Comenzar a usar la API: quick_start.md
- Filtrar y transformar las series: additional_parameters.md
- Integrar la API en planillas de c√°lculo: spreadsheet_integration.md
- Referencia API: api_reference.md
- Proyectos de terceros: third_party.md
theme: readthedocs
